More restrictions on file changes

diff --git a/.github/workflows/check-files-changes.yml b/.github/workflows/check-files-changes.yml
--- a/.github/workflows/check-files-changes.yml
+++ b/.github/workflows/check-files-changes.yml
@@ -16,8 +16,16 @@ jobs:
       run: |
         changed_files=$(git diff --name-only HEAD^ HEAD)
         for file in $changed_files; do
-          if [[ ! $file =~ .*\.py$ ]]; then  # Any python file in any directory is allowed
-            echo "Error: $file cannot be changed. Only python files are allowed."
-            exit 1
-          fi
+            if [[ ! $file =~ ^requirements.txt/ ]]; then  # requirements files are not allowed
+                echo "Error: $file cannot be changed. requirements.txt is restricted."
+                exit 1
+            fi
+            if [[ ! $file =~ ^.github/ ]]; then  # Workflow files are not allowed
+                echo "Error: $file cannot be changed. .github is restricted."
+                exit 1
+            fi
+            if [[ ! $file =~ .*\.py$ ]]; then  # Any python file in any directory is allowed
+                echo "Error: $file cannot be changed. Only python files are allowed."
+                exit 1
+            fi
         done
